price=input("price")
discount=input("discount")
vat=input("vat")
base = float(price) * (1 - float(discount)/100)
vat_amount = float(base) * (float(vat)/100)
total = float(base) + float(vat_amount)
print(f"База после скидки: {base:.2f} ₽")
print(f"НДС:               {vat_amount:.2f} ₽")
print(f"Итого к оплате:    {total:.2f} ₽")